### ISSUE TITLE
Missing OpenStreetMap credits

### ISSUE THREAD

**Issue by harry-wood** [tomjohnneill/ship-stuck#4]
Strange the way vesselfinder.com provides this map embedding thing, but doesn't include the map credits correctly. On vesselfinder.com itself, they show a map with a little "i" button appearing on the bottom right, which reaveals OpenStreetMap credits, but for some reason they've dropped that from the embedded map.

I've sent them a wee message on the contact form to point this out. With a bit of luck the might fix this issue at their end, but otherwise maybe you're supposed to credit OpenStreetMap yourself, e.g. just under the map in a small font ([how?](https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#How_should_I_attribute_you.3F))

**Comment by tomjohnneill** [comment]
Yeah absolutely, I'll get on that now.
